export const METATAGS = [
    { "category": "PRODUCT", "text": "guitarras" },
    { "category": "PRODUCT", "text": "pianos" },
    { "category": "PRODUCT", "text": "baterías" },
    { "category": "PRODUCT", "text": "violines" },
    { "category": "PRODUCT", "text": "saxofones" },
    { "category": "PRODUCT", "text": "trumpetas" },
    { "category": "PRODUCT", "text": "trombones" },
    { "category": "PRODUCT", "text": "clarinetes" },
    { "category": "PRODUCT", "text": "flautas" },
    { "category": "PRODUCT", "text": "trombones" },
    { "category": "PRODUCT", "text": "acordeones" },
    { "category": "PRODUCT", "text": "teclados" },
    { "category": "PRODUCT", "text": "armónicas" },
    { "category": "PRODUCT", "text": "bajos" },
    { "category": "PRODUCT", "text": "mandolinas" },
    { "category": "PRODUCT", "text": "ukeleles" },
    { "category": "PRODUCT", "text": "banjos" },
    { "category": "PRODUCT", "text": "cajas" },
    { "category": "PRODUCT", "text": "congas" },
    { "category": "PRODUCT", "text": "bongos" },
    { "category": "PRODUCT", "text": "djembes" },
    { "category": "PRODUCT", "text": "cajones" },
    { "category": "PRODUCT", "text": "campanas" },
    { "category": "PRODUCT", "text": "maracas" },
    { "category": "PRODUCT", "text": "panderetas" },
    { "category": "PRODUCT", "text": "timbal" },
    { "category": "PRODUCT", "text": "baterías electrónicas" },
    { "category": "PRODUCT", "text": "pedales" },
    { "category": "PRODUCT", "text": "amplificadores" },
    { "category": "PRODUCT", "text": "monitores" },
    { "category": "PRODUCT", "text": "micrófonos" },
    { "category": "PRODUCT", "text": "auriculares" },
    { "category": "PRODUCT", "text": "interfaces" },
    { "category": "PRODUCT", "text": "mezcladoras" },
    { "category": "PRODUCT", "text": "controladores" },
    { "category": "PRODUCT", "text": "cuerdas" },
    { "category": "PRODUCT", "text": "baquetas" },
    { "category": "PRODUCT", "text": "afinadores" },
    { "category": "PRODUCT", "text": "soportes" },
    { "category": "PRODUCT", "text": "estrados" },
    { "category": "PRODUCT", "text": "conciertos" },
    { "category": "PRODUCT", "text": "partituras" },
    { "category": "PRODUCT", "text": "libros" },
    { "category": "PRODUCT", "text": "CDs" },
    { "category": "PRODUCT", "text": "vinilos" },
    { "category": "PRODUCT", "text": "descargas" },
    { "category": "PRODUCT", "text": "altavoces" },
    { "category": "PRODUCT", "text": "acústica" },
    { "category": "PRODUCT", "text": "diana" },
    { "category": "PRODUCT", "text": "trompetas" },
    { "category": "PRODUCT", "text": "gaita" },
    { "category": "PRODUCT", "text": "saxo" },
    { "category": "PRODUCT", "text": "violonchelo" },
    { "category": "PRODUCT", "text": "mandolina" },
    { "category": "PRODUCT", "text": "arpa" },
    { "category": "PRODUCT", "text": "sitar" },
    { "category": "PRODUCT", "text": "lira" },
    { "category": "PRODUCT", "text": "zurna" },
    { "category": "PRODUCT", "text": "bandoneón" },
    { "category": "PRODUCT", "text": "trombón" },
    { "category": "PRODUCT", "text": "trombón" },
    { "category": "PRODUCT", "text": "saxofón" },
    { "category": "PRODUCT", "text": "violín" },
    { "category": "PRODUCT", "text": "guitarra" },
    { "category": "PRODUCT", "text": "piano" },
    { "category": "PRODUCT", "text": "bajo" },
    { "category": "PRODUCT", "text": "batería" },
    { "category": "PRODUCT", "text": "teclado" },
    { "category": "PRODUCT", "text": "armónica" },
    { "category": "PRODUCT", "text": "marimba" },
    { "category": "PRODUCT", "text": "xilófono" },
    { "category": "PRODUCT", "text": "luthier" },
    { "category": "PRODUCT", "text": "cartucho" },
    { "category": "PRODUCT", "text": "micrófono" },
    { "category": "PRODUCT", "text": "amplificador" },
    { "category": "PRODUCT", "text": "pedal" },
    { "category": "PRODUCT", "text": "mezclador" },
    { "category": "PRODUCT", "text": "interface" },
    { "category": "PRODUCT", "text": "monitor" },
    { "category": "PRODUCT", "text": "auricular" },
    { "category": "PRODUCT", "text": "cable" },
    { "category": "PRODUCT", "text": "soporte" },
    { "category": "PRODUCT", "text": "stand" },
    { "category": "PRODUCT", "text": "estrado" },
    { "category": "PRODUCT", "text": "partitura" },
    { "category": "PRODUCT", "text": "libro" },
    { "category": "PRODUCT", "text": "CD" },
    { "category": "PRODUCT", "text": "vinilo" },
    { "category": "PRODUCT", "text": "smartphones" },
    { "category": "PRODUCT", "text": "laptops" },
    { "category": "PRODUCT", "text": "relojes inteligentes" },
    { "category": "PRODUCT", "text": "auriculares" },
    { "category": "PRODUCT", "text": "tabletas" },
    { "category": "PRODUCT", "text": "televisores" },
    { "category": "PRODUCT", "text": "cámaras" },
    { "category": "PRODUCT", "text": "consolas de videojuegos" },
    { "category": "PRODUCT", "text": "impresoras" },
    { "category": "PRODUCT", "text": "ratones" },
    { "category": "PRODUCT", "text": "teclados" },
    { "category": "PRODUCT", "text": "discos duros externos" },
    { "category": "PRODUCT", "text": "altavoces bluetooth" },
    { "category": "PRODUCT", "text": "proyectores" },
    { "category": "PRODUCT", "text": "monitores" },
    { "category": "PRODUCT", "text": "routers" },
    { "category": "PRODUCT", "text": "memorias USB" },
    { "category": "PRODUCT", "text": "refrigeradores" },
    { "category": "PRODUCT", "text": "lavadoras" },
    { "category": "PRODUCT", "text": "aspiradoras" },
    { "category": "PRODUCT", "text": "microondas" },
    { "category": "PRODUCT", "text": "hornos eléctricos" },
    { "category": "PRODUCT", "text": "licuadoras" },
    { "category": "PRODUCT", "text": "cafeteras" },
    { "category": "PRODUCT", "text": "ventiladores" },
    { "category": "PRODUCT", "text": "aire acondicionado" },
    { "category": "PRODUCT", "text": "calentadores" },
    { "category": "PRODUCT", "text": "bicicletas" },
    { "category": "PRODUCT", "text": "scooters eléctricos" },
    { "category": "PRODUCT", "text": "patinetas" },
    { "category": "PRODUCT", "text": "drones" },
    { "category": "PRODUCT", "text": "cascos de realidad virtual" },
    { "category": "PRODUCT", "text": "controladores de videojuegos" },
    { "category": "PRODUCT", "text": "auriculares para juegos" },
    { "category": "PRODUCT", "text": "sillas gamer" },
    { "category": "PRODUCT", "text": "mesas de juego" },
    { "category": "PRODUCT", "text": "equipos de sonido" },
    { "category": "PRODUCT", "text": "cámaras de seguridad" },
    { "category": "PRODUCT", "text": "alarmas" },
    { "category": "PRODUCT", "text": "domótica" },
    { "category": "PRODUCT", "text": "cerraduras inteligentes" },
    { "category": "PRODUCT", "text": "robots de limpieza" },
    { "category": "PRODUCT", "text": "juguetes" },
    { "category": "PRODUCT", "text": "juegos de mesa" },
    { "category": "PRODUCT", "text": "libros" },
    { "category": "PRODUCT", "text": "ropa" },
    { "category": "PRODUCT", "text": "calzado" },
    { "category": "PRODUCT", "text": "accesorios" },
    { "category": "PRODUCT", "text": "bolsos" },
    { "category": "PRODUCT", "text": "relojes" },
    { "category": "PRODUCT", "text": "joyería" },
    { "category": "PRODUCT", "text": "gafas de sol" },
    { "category": "PRODUCT", "text": "ropa deportiva" },
    { "category": "PRODUCT", "text": "equipos de gimnasio" },
    { "category": "PRODUCT", "text": "suplementos nutricionales" },
    { "category": "PRODUCT", "text": "bicicletas estáticas" },
    { "category": "PRODUCT", "text": "cintas de correr" },
    { "category": "PRODUCT", "text": "máquinas de remo" },
    { "category": "PRODUCT", "text": "pesas" },
    { "category": "PRODUCT", "text": "bandas elásticas" },
    { "category": "PRODUCT", "text": "colchonetas de yoga" },
    { "category": "PRODUCT", "text": "trajes de baño" },
    { "category": "PRODUCT", "text": "equipos de buceo" },
    { "category": "PRODUCT", "text": "tablas de surf" },
    { "category": "PRODUCT", "text": "patines en línea" },
    { "category": "PRODUCT", "text": "equipos de camping" },
    { "category": "PRODUCT", "text": "tiendas de campaña" },
    { "category": "PRODUCT", "text": "sacos de dormir" },
    { "category": "PRODUCT", "text": "linternas" },
    { "category": "PRODUCT", "text": "cuchillos de supervivencia" },
    { "category": "PRODUCT", "text": "mochilas" },
    { "category": "PRODUCT", "text": "equipos de pesca" },
    { "category": "PRODUCT", "text": "cañas de pescar" },
    { "category": "PRODUCT", "text": "carretes de pesca" },
    { "category": "PRODUCT", "text": "señuelos de pesca" },
    { "category": "PRODUCT", "text": "equipos de caza" },
    { "category": "PRODUCT", "text": "arcos" },
    { "category": "PRODUCT", "text": "ballestas" },
    { "category": "PRODUCT", "text": "objetivos de tiro" },
    { "category": "PRODUCT", "text": "binoculares" },
    { "category": "PRODUCT", "text": "telescopios" },
    { "category": "PRODUCT", "text": "microscopios" },
    { "category": "PRODUCT", "text": "equipos de laboratorio" },
    { "category": "PRODUCT", "text": "productos de oficina" },
    { "category": "PRODUCT", "text": "sillas de oficina" },
    { "category": "PRODUCT", "text": "escritorios" },
    { "category": "PRODUCT", "text": "archivadores" },
    { "category": "PRODUCT", "text": "papelería" },
    { "category": "PRODUCT", "text": "calculadoras" },
    { "category": "PRODUCT", "text": "proyectores de oficina" },
    { "category": "PRODUCT", "text": "pantallas de proyección" },
    { "category": "PRODUCT", "text": "equipos de red" },
    { "category": "PRODUCT", "text": "switches de red" },
    { "category": "PRODUCT", "text": "cables de red" },
    { "category": "PRODUCT", "text": "servidores" },
    { "category": "PRODUCT", "text": "equipos de almacenamiento" },
    { "category": "PRODUCT", "text": "productos de belleza" },
    { "category": "PRODUCT", "text": "maquillaje" },
    { "category": "PRODUCT", "text": "productos para el cabello" },
    { "category": "PRODUCT", "text": "cuidado de la piel" },
    { "category": "PRODUCT", "text": "fragancias" },
    { "category": "PRODUCT", "text": "esmaltes de uñas" },
    { "category": "PRODUCT", "text": "herramientas de belleza" },
    { "category": "PRODUCT", "text": "cuidado dental" },
    { "category": "PRODUCT", "text": "productos para bebés" },
    { "category": "PRODUCT", "text": "pañales" },
    { "category": "PRODUCT", "text": "biberones" },
    { "category": "PRODUCT", "text": "cochecitos" },
    { "category": "PRODUCT", "text": "sillas de auto" },
    { "category": "PRODUCT", "text": "ropa de bebé" },
    { "category": "PRODUCT", "text": "juguetes para bebés" },
    { "category": "PRODUCT", "text": "muebles para bebés" },
    { "category": "PRODUCT", "text": "sistemas de seguridad para bebés" },
    { "category": "PRODUCT", "text": "monitores para bebés" },
    { "category": "PRODUCT", "text": "humificadores para bebés" },
    { "category": "CAR", "text": "sedan" },
    { "category": "CAR", "text": "SUV" },
    { "category": "CAR", "text": "híbridos" },
    { "category": "CAR", "text": "eléctricos" },
    { "category": "CAR", "text": "deportivos" },
    { "category": "CAR", "text": "pickup" },
    { "category": "CAR", "text": "convertibles" },
    { "category": "CAR", "text": "camiones" },
    { "category": "CAR", "text": "minivan" },
    { "category": "CAR", "text": "autos compactos" },
    { "category": "CAR", "text": "autos de lujo" },
    { "category": "CAR", "text": "autos clásicos" },
    { "category": "CAR", "text": "autos deportivos" },
    { "category": "CAR", "text": "autobuses" },
    { "category": "CAR", "text": "vans" },
    { "category": "CAR", "text": "jeeps" },
    { "category": "CAR", "text": "todoterreno" },
    { "category": "CAR", "text": "automóviles" },
    { "category": "CAR", "text": "autos" },
    { "category": "CAR", "text": "vehículos" },
    { "category": "CAR", "text": "sedanes de lujo" },
    { "category": "CAR", "text": "SUV de lujo" },
    { "category": "CAR", "text": "camionetas" },
    { "category": "CAR", "text": "híbridos enchufables" },
    { "category": "CAR", "text": "eléctricos de largo alcance" },
    { "category": "CAR", "text": "autos de alto rendimiento" },
    { "category": "CAR", "text": "hatchbacks" },
    { "category": "CAR", "text": "autos pequeños" },
    { "category": "CAR", "text": "autos familiares" },
    { "category": "CAR", "text": "sedanes medianos" },
    { "category": "CAR", "text": "SUV compactos" },
    { "category": "CAR", "text": "camiones ligeros" },
    { "category": "CAR", "text": "camiones pesados" },
    { "category": "CAR", "text": "vehículos comerciales" },
    { "category": "CAR", "text": "autos de segunda mano" },
    { "category": "CAR", "text": "autos usados" },
    { "category": "CAR", "text": "vehículos seminuevos" },
    { "category": "CAR", "text": "autos de ocasión" },
    { "category": "CAR", "text": "vehículos certificados" },
    { "category": "CAR", "text": "autos de agencia" },
    { "category": "CAR", "text": "autos reacondicionados" },
    { "category": "CAR", "text": "vehículos de demostración" },
    { "category": "CAR", "text": "autos ex-renta" },
    { "category": "CAR", "text": "vehículos de flotilla" },
    { "category": "CAR", "text": "autos en oferta" },
    { "category": "CAR", "text": "vehículos de exportación" },
    { "category": "CAR", "text": "autos importados" },
    { "category": "CAR", "text": "autos de lujo usados" },
    { "category": "CAR", "text": "autos deportivos usados" },
    { "category": "CAR", "text": "autos clásicos usados" },
    { "category": "CAR", "text": "vehículos comerciales usados" },
    { "category": "CAR", "text": "camionetas usadas" },
    { "category": "CAR", "text": "SUV usadas" },
    { "category": "CAR", "text": "minivans usadas" },
    { "category": "CAR", "text": "autos económicos" },
    { "category": "CAR", "text": "autos baratos" },
    { "category": "CAR", "text": "vehículos asequibles" },
    { "category": "CAR", "text": "autos de bajo costo" },
    { "category": "CAR", "text": "autos a buen precio" },
    { "category": "CAR", "text": "vehículos accesibles" },
    { "category": "CAR", "text": "autos de menos de $5000" },
    { "category": "CAR", "text": "autos de menos de $10000" },
    { "category": "CAR", "text": "vehículos de menos de $15000" },
    { "category": "CAR", "text": "autos económicos nuevos" },
    { "category": "CAR", "text": "autos baratos nuevos" },
    { "category": "CAR", "text": "vehículos asequibles nuevos" },
    { "category": "CAR", "text": "autos de bajo costo nuevos" },
    { "category": "CAR", "text": "autos a buen precio nuevos" },
    { "category": "CAR", "text": "vehículos accesibles nuevos" },
    { "category": "CAR", "text": "autos de menos de $20000 nuevos" },
    { "category": "CAR", "text": "autos de menos de $25000 nuevos" },
    { "category": "CAR", "text": "vehículos de menos de $30000 nuevos" },
    { "category": "CAR", "text": "autos de alta gama" },
    { "category": "CAR", "text": "autos de lujo nuevos" },
    { "category": "CAR", "text": "vehículos premium" },
    { "category": "CAR", "text": "autos exclusivos" },
    { "category": "CAR", "text": "autos de alta gama" },
    { "category": "CAR", "text": "vehículos de lujo" },
    { "category": "CAR", "text": "autos deportivos de lujo" },
    { "category": "CAR", "text": "autos clásicos de lujo" },
    { "category": "CAR", "text": "vehículos comerciales de lujo" },
    { "category": "CAR", "text": "camionetas de lujo" },
    { "category": "CAR", "text": "SUV de lujo nuevos" },
    { "category": "CAR", "text": "minivans de lujo" },
    { "category": "CAR", "text": "autos eléctricos de lujo" },
    { "category": "CAR", "text": "autos híbridos de lujo" },
    { "category": "CAR", "text": "vehículos híbridos enchufables de lujo" },
    { "category": "CAR", "text": "autos eléctricos de largo alcance de lujo" },
    { "category": "CAR", "text": "autos deportivos de alto rendimiento de lujo" },
    { "category": "CAR", "text": "vehículos premium de lujo" },
    { "category": "CAR", "text": "autos de lujo exclusivos" },
    { "category": "CAR", "text": "autos de alta gama exclusivos" },
    { "category": "CAR", "text": "vehículos de lujo exclusivos" },
    { "category": "SERVICES", "text": "limpieza" },
    { "category": "SERVICES", "text": "jardinería" },
    { "category": "SERVICES", "text": "reparaciones" },
    { "category": "SERVICES", "text": "transporte" },
    { "category": "SERVICES", "text": "mudanzas" },
    { "category": "SERVICES", "text": "fontanería" },
    { "category": "SERVICES", "text": "electricidad" },
    { "category": "SERVICES", "text": "pintura" },
    { "category": "SERVICES", "text": "cerrajería" },
    { "category": "SERVICES", "text": "limpieza de alfombras" },
    { "category": "SERVICES", "text": "limpieza de ventanas" },
    { "category": "SERVICES", "text": "limpieza de oficinas" },
    { "category": "SERVICES", "text": "mantenimiento de piscinas" },
    { "category": "SERVICES", "text": "mantenimiento de jardines" },
    { "category": "SERVICES", "text": "desinfección" },
    { "category": "SERVICES", "text": "control de plagas" },
    { "category": "SERVICES", "text": "fumigación" },
    { "category": "SERVICES", "text": "limpieza de canaletas" },
    { "category": "SERVICES", "text": "lavado a presión" },
    { "category": "SERVICES", "text": "limpieza de chimeneas" },
    { "category": "SERVICES", "text": "limpieza de tejados" },
    { "category": "SERVICES", "text": "limpieza de patios" },
    { "category": "SERVICES", "text": "limpieza de garajes" },
    { "category": "SERVICES", "text": "limpieza de sótanos" },
    { "category": "SERVICES", "text": "limpieza de tapicerías" },
    { "category": "SERVICES", "text": "limpieza de autos" },
    { "category": "SERVICES", "text": "lavado de autos" },
    { "category": "SERVICES", "text": "detailing de autos" },
    { "category": "SERVICES", "text": "cuidado de autos" },
    { "category": "SERVICES", "text": "tintado de ventanas" },
    { "category": "SERVICES", "text": "cambio de aceite" },
    { "category": "SERVICES", "text": "reparación de neumáticos" },
    { "category": "SERVICES", "text": "reparación de frenos" },
    { "category": "SERVICES", "text": "mantenimiento de autos" },
    { "category": "SERVICES", "text": "mecánica" },
    { "category": "SERVICES", "text": "mantenimiento de vehículos" },
    { "category": "SERVICES", "text": "revisión de vehículos" },
    { "category": "SERVICES", "text": "inspección de vehículos" },
    { "category": "SERVICES", "text": "reparación de autos" },
    { "category": "SERVICES", "text": "taller mecánico" },
    { "category": "SERVICES", "text": "reparación de motores" },
    { "category": "SERVICES", "text": "reparación de transmisiones" },
    { "category": "SERVICES", "text": "reparación de frenos" },
    { "category": "SERVICES", "text": "reparación de suspensión" },
    { "category": "SERVICES", "text": "alineación de ruedas" },
    { "category": "SERVICES", "text": "equilibrado de ruedas" },
    { "category": "SERVICES", "text": "cambio de neumáticos" },
    { "category": "SERVICES", "text": "rotación de neumáticos" },
    { "category": "SERVICES", "text": "reparación de sistemas de escape" },
    { "category": "SERVICES", "text": "reparación de aire acondicionado" },
    { "category": "SERVICES", "text": "reparación de calefacción" },
    { "category": "SERVICES", "text": "reparación de sistemas eléctricos" },
    { "category": "SERVICES", "text": "reparación de sistemas de dirección" },
    { "category": "SERVICES", "text": "reparación de sistemas de combustible" },
    { "category": "SERVICES", "text": "reparación de sistemas de refrigeración" },
    { "category": "SERVICES", "text": "reparación de parabrisas" },
    { "category": "SERVICES", "text": "cambio de parabrisas" },
    { "category": "SERVICES", "text": "reparación de vidrios de autos" },
    { "category": "SERVICES", "text": "tintado de vidrios de autos" },
    { "category": "SERVICES", "text": "pulido de faros" },
    { "category": "SERVICES", "text": "reparación de faros" },
    { "category": "SERVICES", "text": "instalación de sistemas de sonido" },
    { "category": "SERVICES", "text": "instalación de sistemas de navegación" },
    { "category": "SERVICES", "text": "instalación de sistemas de seguridad" },
    { "category": "SERVICES", "text": "reparación de sistemas de seguridad" },
    { "category": "SERVICES", "text": "reparación de sistemas de navegación" },
    { "category": "SERVICES", "text": "reparación de sistemas de sonido" },
    { "category": "SERVICES", "text": "mantenimiento de sistemas de sonido" },
    { "category": "SERVICES", "text": "mantenimiento de sistemas de navegación" },
    { "category": "SERVICES", "text": "mantenimiento de sistemas de seguridad" },
    { "category": "SERVICES", "text": "reparación de sistemas de audio" },
    { "category": "SERVICES", "text": "reparación de sistemas de video" },
    { "category": "SERVICES", "text": "reparación de sistemas de entretenimiento" },
    { "category": "SERVICES", "text": "mantenimiento de sistemas de entretenimiento" },
    { "category": "SERVICES", "text": "reparación de sistemas de comunicación" },
    { "category": "SERVICES", "text": "mantenimiento de sistemas de comunicación" },
    { "category": "SERVICES", "text": "reparación de sistemas de navegación GPS" },
    { "category": "SERVICES", "text": "mantenimiento de sistemas de navegación GPS" },
    { "category": "SERVICES", "text": "instalación de sistemas de navegación GPS" },
    { "category": "SERVICES", "text": "instalación de sistemas de entretenimiento" },
    { "category": "SERVICES", "text": "mantenimiento de sistemas de entretenimiento" },
    { "category": "SERVICES", "text": "reparación de sistemas de audio y video" },
    { "category": "HOUSES", "text": "alquiler" },
    { "category": "HOUSES", "text": "venta" },
    { "category": "HOUSES", "text": "apartamentos" },
    { "category": "HOUSES", "text": "casas nuevas" },
    { "category": "HOUSES", "text": "casas usadas" },
    { "category": "HOUSES", "text": "apartamentos nuevos" },
    { "category": "HOUSES", "text": "apartamentos usados" },
    { "category": "HOUSES", "text": "casas de lujo" },
    { "category": "HOUSES", "text": "apartamentos de lujo" },
    { "category": "HOUSES", "text": "casas económicas" },
    { "category": "HOUSES", "text": "apartamentos económicos" },
    { "category": "HOUSES", "text": "casas grandes" },
    { "category": "HOUSES", "text": "apartamentos grandes" },
    { "category": "HOUSES", "text": "casas pequeñas" },
    { "category": "HOUSES", "text": "apartamentos pequeños" },
    { "category": "HOUSES", "text": "casas familiares" },
    { "category": "HOUSES", "text": "apartamentos familiares" },
    { "category": "HOUSES", "text": "casas modernas" },
    { "category": "HOUSES", "text": "apartamentos modernos" },
    { "category": "HOUSES", "text": "casas tradicionales" },
    { "category": "HOUSES", "text": "apartamentos tradicionales" },
    { "category": "HOUSES", "text": "casas rurales" },
    { "category": "HOUSES", "text": "apartamentos rurales" },
    { "category": "HOUSES", "text": "casas en la ciudad" },
    { "category": "HOUSES", "text": "apartamentos en la ciudad" },
    { "category": "HOUSES", "text": "casas en el campo" },
    { "category": "HOUSES", "text": "apartamentos en el campo" },
    { "category": "HOUSES", "text": "casas en la playa" },
    { "category": "HOUSES", "text": "apartamentos en la playa" },
    { "category": "HOUSES", "text": "casas en la montaña" },
    { "category": "HOUSES", "text": "apartamentos en la montaña" },
    { "category": "HOUSES", "text": "casas con piscina" },
    { "category": "HOUSES", "text": "apartamentos con piscina" },
    { "category": "HOUSES", "text": "casas con jardín" },
    { "category": "HOUSES", "text": "apartamentos con jardín" },
    { "category": "HOUSES", "text": "casas con terraza" },
    { "category": "HOUSES", "text": "apartamentos con terraza" },
    { "category": "HOUSES", "text": "casas con balcón" },
    { "category": "HOUSES", "text": "apartamentos con balcón" },
    { "category": "HOUSES", "text": "casas con garaje" },
    { "category": "HOUSES", "text": "apartamentos con garaje" },
    { "category": "HOUSES", "text": "casas con sótano" },
    { "category": "HOUSES", "text": "apartamentos con sótano" },
    { "category": "HOUSES", "text": "casas con ático" },
    { "category": "HOUSES", "text": "apartamentos con ático" },
    { "category": "HOUSES", "text": "casas con ascensor" },
    { "category": "HOUSES", "text": "apartamentos con ascensor" },
    { "category": "HOUSES", "text": "casas con vista al mar" },
    { "category": "HOUSES", "text": "apartamentos con vista al mar" },
    { "category": "HOUSES", "text": "casas con vista a la montaña" },
    { "category": "HOUSES", "text": "apartamentos con vista a la montaña" },
    { "category": "HOUSES", "text": "casas con vista panorámica" },
    { "category": "HOUSES", "text": "apartamentos con vista panorámica" },
    { "category": "HOUSES", "text": "casas con chimenea" },
    { "category": "HOUSES", "text": "apartamentos con chimenea" },
    { "category": "HOUSES", "text": "casas con calefacción" },
    { "category": "HOUSES", "text": "apartamentos con calefacción" },
    { "category": "HOUSES", "text": "casas con aire acondicionado" },
    { "category": "HOUSES", "text": "apartamentos con aire acondicionado" },
    { "category": "HOUSES", "text": "casas con energía solar" },
    { "category": "HOUSES", "text": "apartamentos con energía solar" },
    { "category": "HOUSES", "text": "casas con jardín grande" },
    { "category": "HOUSES", "text": "apartamentos con jardín grande" },
    { "category": "HOUSES", "text": "casas con patio" },
    { "category": "HOUSES", "text": "apartamentos con patio" },
    { "category": "HOUSES", "text": "casas con bodega" },
    { "category": "HOUSES", "text": "apartamentos con bodega" },
    { "category": "HOUSES", "text": "casas con cuarto de servicio" },
    { "category": "HOUSES", "text": "apartamentos con cuarto de servicio" },
    { "category": "HOUSES", "text": "casas con lavadero" },
    { "category": "HOUSES", "text": "apartamentos con lavadero" },
    { "category": "HOUSES", "text": "casas con despensa" },
    { "category": "HOUSES", "text": "apartamentos con despensa" },
    { "category": "HOUSES", "text": "casas con cocina equipada" },
    { "category": "HOUSES", "text": "apartamentos con cocina equipada" },
    { "category": "HOUSES", "text": "casas con baño de visitas" },
    { "category": "HOUSES", "text": "apartamentos con baño de visitas" },
    { "category": "HOUSES", "text": "casas con vestidor" },
    { "category": "HOUSES", "text": "apartamentos con vestidor" },
    { "category": "HOUSES", "text": "casas con estudio" },
    { "category": "HOUSES", "text": "apartamentos con estudio" },
    { "category": "HOUSES", "text": "casas con oficina" },
    { "category": "HOUSES", "text": "apartamentos con oficina" },
    { "category": "HOUSES", "text": "casas con gimnasio" },
    { "category": "HOUSES", "text": "apartamentos con gimnasio" },
    { "category": "HOUSES", "text": "casas con sala de juegos" },
    { "category": "HOUSES", "text": "apartamentos con sala de juegos" },
    { "category": "HOUSES", "text": "casas con biblioteca" },
    { "category": "HOUSES", "text": "apartamentos con biblioteca" },
    { "category": "HOUSES", "text": "casas con salón de usos múltiples" },
    { "category": "HOUSES", "text": "apartamentos con salón de usos múltiples" },
    { "category": "HOUSES", "text": "casas con sala de cine" },
    { "category": "HOUSES", "text": "apartamentos con sala de cine" },
    { "category": "HOUSES", "text": "casas con terraza techada" },
    { "category": "HOUSES", "text": "apartamentos con terraza techada" },
    { "category": "HOUSES", "text": "casas con terraza al aire libre" },
    { "category": "HOUSES", "text": "apartamentos con terraza al aire libre" },
    { "category": "HOUSES", "text": "casas con terraza con vista al mar" },
    { "category": "HOUSES", "text": "apartamentos con terraza con vista al mar" },
    { "category": "HOUSES", "text": "casas con terraza con vista a la montaña" },
    { "category": "HOUSES", "text": "apartamentos con terraza con vista a la montaña" },
    { "category": "HOUSES", "text": "casas con terraza con vista panorámica" },
    { "category": "HOUSES", "text": "apartamentos con terraza con vista panorámica" },
    { "category": "HOUSES", "text": "casas con alberca" },
    { "category": "HOUSES", "text": "apartamentos con alberca" },
    { "category": "HOUSES", "text": "casas con jacuzzi" },
    { "category": "HOUSES", "text": "apartamentos con jacuzzi" },
    { "category": "HOUSES", "text": "casas con sauna" },
    { "category": "HOUSES", "text": "apartamentos con sauna" },
    { "category": "HOUSES", "text": "casas con spa" },
    { "category": "HOUSES", "text": "apartamentos con spa" },
    { "category": "HOUSES", "text": "casas con cancha de tenis" },
    { "category": "HOUSES", "text": "apartamentos con cancha de tenis" },
    { "category": "HOUSES", "text": "casas con cancha de pádel" },
    { "category": "HOUSES", "text": "apartamentos con cancha de pádel" },
    { "category": "HOUSES", "text": "casas con cancha de fútbol" },
    { "category": "HOUSES", "text": "apartamentos con cancha de fútbol" },
    { "category": "HOUSES", "text": "casas con cancha de baloncesto" },
    { "category": "HOUSES", "text": "apartamentos con cancha de baloncesto" },
    { "category": "HOUSES", "text": "casas con campo de golf" },
    { "category": "HOUSES", "text": "apartamentos con campo de golf" },
    { "category": "HOUSES", "text": "casas con parque" },
    { "category": "HOUSES", "text": "apartamentos con parque" },
    { "category": "HOUSES", "text": "casas con área de juegos infantiles" },
    { "category": "HOUSES", "text": "apartamentos con área de juegos infantiles" },
    { "category": "HOUSES", "text": "casas con zona de barbacoa" },
    { "category": "HOUSES", "text": "apartamentos con zona de barbacoa" },
    { "category": "HOUSES", "text": "casas con sala de eventos" },
    { "category": "HOUSES", "text": "apartamentos con sala de eventos" },
    { "category": "HOUSES", "text": "casas con salón de fiestas" },
    { "category": "HOUSES", "text": "apartamentos con salón de fiestas" },
    { "category": "HOUSES", "text": "casas con zona de juegos" },
    { "category": "HOUSES", "text": "apartamentos con zona de juegos" },
    { "category": "HOUSES", "text": "casas con zona de relajación" },
    { "category": "HOUSES", "text": "apartamentos con zona de relajación" },
    { "category": "HOUSES", "text": "casas con zona de lectura" },
    { "category": "HOUSES", "text": "apartamentos con zona de lectura" },
    { "category": "HOUSES", "text": "casas con zona de meditación" },
    { "category": "HOUSES", "text": "apartamentos con zona de meditación" },
    { "category": "HOUSES", "text": "casas con zona de yoga" },
    { "category": "HOUSES", "text": "apartamentos con zona de yoga" },
    { "category": "HOUSES", "text": "casas con zona de pilates" },
    { "category": "HOUSES", "text": "apartamentos con zona de pilates" },
    { "category": "HOUSES", "text": "casas con zona de crossfit" },
    { "category": "HOUSES", "text": "apartamentos con zona de crossfit" },
    { "category": "HOUSES", "text": "casas con zona de spinning" },
    { "category": "HOUSES", "text": "apartamentos con zona de spinning" },
    { "category": "HOUSES", "text": "casas con zona de fitness" },
    { "category": "HOUSES", "text": "apartamentos con zona de fitness" },
    { "category": "HOUSES", "text": "casas con zona de wellness" },
    { "category": "HOUSES", "text": "apartamentos con zona de wellness" },
    { "category": "HOUSES", "text": "casas con zona de coworking" },
    { "category": "HOUSES", "text": "apartamentos con zona de coworking" },
    { "category": "HOUSES", "text": "casas con zona de negocios" },
    { "category": "HOUSES", "text": "apartamentos con zona de negocios" },
    { "category": "HOUSES", "text": "casas con zona de descanso" },
    { "category": "HOUSES", "text": "apartamentos con zona de descanso" },
    { "category": "HOUSES", "text": "casas con zona de televisión" },
    { "category": "HOUSES", "text": "apartamentos con zona de televisión" },
    { "category": "HOUSES", "text": "casas con zona de videojuegos" },
    { "category": "HOUSES", "text": "apartamentos con zona de videojuegos" },
    { "category": "HOUSES", "text": "casas con zona de comedor" },
    { "category": "HOUSES", "text": "apartamentos con zona de comedor" },
    { "category": "HOUSES", "text": "casas con zona de cocina" },
    { "category": "HOUSES", "text": "apartamentos con zona de cocina" },
    { "category": "HOUSES", "text": "casas con zona de lavandería" },
    { "category": "HOUSES", "text": "apartamentos con zona de lavandería" },
    { "category": "HOUSES", "text": "casas con zona de planchado" },
    { "category": "HOUSES", "text": "apartamentos con zona de planchado" },
    { "category": "HOUSES", "text": "casas con zona de almacenamiento" },
    { "category": "HOUSES", "text": "apartamentos con zona de almacenamiento" },
    { "category": "HOUSES", "text": "casas con zona de bicicletas" },
    { "category": "HOUSES", "text": "apartamentos con zona de bicicletas" },
    { "category": "HOUSES", "text": "casas con zona de mascotas" },
    { "category": "HOUSES", "text": "apartamentos con zona de mascotas" },
    { "category": "HOUSES", "text": "casas con zona de fumadores" },
    { "category": "HOUSES", "text": "apartamentos con zona de fumadores" },
    { "category": "HOUSES", "text": "casas con zona de no fumadores" },
    { "category": "HOUSES", "text": "apartamentos con zona de no fumadores" },
    { "category": "HOUSES", "text": "casas con acceso para discapacitados" },
    { "category": "HOUSES", "text": "apartamentos con acceso para discapacitados" },
    { "category": "HOUSES", "text": "casas con ascensor para discapacitados" },
    { "category": "HOUSES", "text": "apartamentos con ascensor para discapacitados" },
    { "category": "HOUSES", "text": "casas con acceso para sillas de ruedas" },
    { "category": "HOUSES", "text": "apartamentos con acceso para sillas de ruedas" },
    { "category": "HOUSES", "text": "casas con puertas automáticas" },
    { "category": "HOUSES", "text": "apartamentos con puertas automáticas" },
    { "category": "HOUSES", "text": "casas con control de acceso" },
    { "category": "HOUSES", "text": "apartamentos con control de acceso" },
    { "category": "HOUSES", "text": "casas con seguridad 24 horas" },
    { "category": "HOUSES", "text": "apartamentos con seguridad 24 horas" },
    { "category": "HOUSES", "text": "casas con cámaras de seguridad" },
    { "category": "HOUSES", "text": "apartamentos con cámaras de seguridad" },
    { "category": "HOUSES", "text": "casas con alarma de seguridad" },
    { "category": "HOUSES", "text": "apartamentos con alarma de seguridad" },
    { "category": "HOUSES", "text": "casas con vigilancia" },
    { "category": "HOUSES", "text": "apartamentos con vigilancia" },
    { "category": "HOUSES", "text": "casas con portero" },
    { "category": "HOUSES", "text": "apartamentos con portero" },
    { "category": "HOUSES", "text": "casas con conserje" },
    { "category": "HOUSES", "text": "apartamentos con conserje" },
    { "category": "HOUSES", "text": "casas con servicio de limpieza" },
    { "category": "HOUSES", "text": "apartamentos con servicio de limpieza" },
    { "category": "HOUSES", "text": "casas con servicio de lavandería" },
    { "category": "HOUSES", "text": "apartamentos con servicio de lavandería" },
    { "category": "HOUSES", "text": "casas con servicio de planchado" },
    { "category": "HOUSES", "text": "apartamentos con servicio de planchado" },
    { "category": "HOUSES", "text": "casas con servicio de comida" },
    { "category": "HOUSES", "text": "apartamentos con servicio de comida" },
    { "category": "HOUSES", "text": "casas con servicio de transporte" },
    { "category": "HOUSES", "text": "apartamentos con servicio de transporte" },
    { "category": "HOUSES", "text": "casas con servicio de mensajería" },
    { "category": "HOUSES", "text": "apartamentos con servicio de mensajería" },
    { "category": "HOUSES", "text": "casas con servicio de mantenimiento" },
    { "category": "HOUSES", "text": "apartamentos con servicio de mantenimiento" },
    { "category": "HOUSES", "text": "casas con servicio de jardinería" },
    { "category": "HOUSES", "text": "apartamentos con servicio de jardinería" },
    { "category": "HOUSES", "text": "casas con servicio de reparación" },
    { "category": "HOUSES", "text": "apartamentos con servicio de reparación" },
    { "category": "HOUSES", "text": "casas con servicio de emergencia" },
    { "category": "HOUSES", "text": "apartamentos con servicio de emergencia" },
    { "category": "HOUSES", "text": "casas con servicio de concierge" },
    { "category": "HOUSES", "text": "apartamentos con servicio de concierge" },
    { "category": "HOUSES", "text": "casas con servicio de valet parking" },
    { "category": "HOUSES", "text": "apartamentos con servicio de valet parking" },
    { "category": "HOUSES", "text": "casas con servicio de catering" },
    { "category": "HOUSES", "text": "apartamentos con servicio de catering" },
    { "category": "HOUSES", "text": "casas con servicio de banquetes" },
    { "category": "HOUSES", "text": "apartamentos con servicio de banquetes" },
    { "category": "HOUSES", "text": "casas con servicio de eventos" },
    { "category": "HOUSES", "text": "apartamentos con servicio de eventos" },
    { "category": "HOUSES", "text": "casas con servicio de planificador" },
    { "category": "HOUSES", "text": "apartamentos con servicio de planificador" },
    { "category": "HOUSES", "text": "casas con servicio de organizador" },
    { "category": "HOUSES", "text": "apartamentos con servicio de organizador" },
    { "category": "HOUSES", "text": "casas con servicio de decorador" },
    { "category": "HOUSES", "text": "apartamentos con servicio de decorador" },
    { "category": "HOUSES", "text": "casas con servicio de florista" },
    { "category": "HOUSES", "text": "apartamentos con servicio de florista" },
    { "category": "HOUSES", "text": "casas con servicio de DJ" },
    { "category": "HOUSES", "text": "apartamentos con servicio de DJ" },
    { "category": "HOUSES", "text": "casas con servicio de música en vivo" },
    { "category": "HOUSES", "text": "apartamentos con servicio de música en vivo" },
    { "category": "HOUSES", "text": "casas con servicio de karaoke" },
    { "category": "HOUSES", "text": "apartamentos con servicio de karaoke" },
    { "category": "HOUSES", "text": "casas con servicio de proyección" },
    { "category": "HOUSES", "text": "apartamentos con servicio de proyección" },
    { "category": "HOUSES", "text": "casas con servicio de grabación" },
    { "category": "HOUSES", "text": "apartamentos con servicio de grabación" },
    { "category": "HOUSES", "text": "casas con servicio de edición" },
    { "category": "HOUSES", "text": "apartamentos con servicio de edición" },
    { "category": "HOUSES", "text": "casas con servicio de fotografía" },
    { "category": "HOUSES", "text": "apartamentos con servicio de fotografía" },
    { "category": "HOUSES", "text": "casas con servicio de vídeo" },
    { "category": "HOUSES", "text": "apartamentos con servicio de vídeo" },
    { "category": "HOUSES", "text": "casas con servicio de streaming" },
    { "category": "HOUSES", "text": "apartamentos con servicio de streaming" },
    { "category": "HOUSES", "text": "casas con servicio de edición de vídeo" },
    { "category": "HOUSES", "text": "apartamentos con servicio de edición de vídeo" },
    { "category": "HOUSES", "text": "casas con servicio de edición de audio" },
    { "category": "HOUSES", "text": "apartamentos con servicio de edición de audio" },
    { "category": "HOUSES", "text": "casas con servicio de edición de imagen" },
    { "category": "HOUSES", "text": "apartamentos con servicio de edición de imagen" },
    { "category": "HOUSES", "text": "casas con servicio de edición de texto" },
    { "category": "HOUSES", "text": "apartamentos con servicio de edición de texto" },
    { "category": "HOUSES", "text": "casas con servicio de impresión" },
    { "category": "HOUSES", "text": "apartamentos con servicio de impresión" },
    { "category": "HOUSES", "text": "casas con servicio de duplicación" },
    { "category": "HOUSES", "text": "apartamentos con servicio de duplicación" },
    { "category": "HOUSES", "text": "casas con servicio de escaneo" },
    { "category": "HOUSES", "text": "apartamentos con servicio de escaneo" },
    { "category": "HOUSES", "text": "casas con servicio de fax" },
    { "category": "HOUSES", "text": "apartamentos con servicio de fax" },
    { "category": "HOUSES", "text": "casas con servicio de mensajería" },
    { "category": "HOUSES", "text": "apartamentos con servicio de mensajería" },
    { "category": "HOUSES", "text": "casas con servicio de paquetería" },
    { "category": "HOUSES", "text": "apartamentos con servicio de paquetería" },
    { "category": "HOUSES", "text": "casas con servicio de correo" },
    { "category": "HOUSES", "text": "apartamentos con servicio de correo" },
    { "category": "HOUSES", "text": "casas con servicio de traducción" },
    { "category": "HOUSES", "text": "apartamentos con servicio de traducción" },
    { "category": "HOUSES", "text": "casas con servicio de interpretación" },
    { "category": "HOUSES", "text": "apartamentos con servicio de interpretación" },
    { "category": "HOUSES", "text": "casas con servicio de asesoría" },
    { "category": "HOUSES", "text": "apartamentos con servicio de asesoría" },
    { "category": "HOUSES", "text": "casas con servicio de consultoría" },
    { "category": "HOUSES", "text": "apartamentos con servicio de consultoría" },
    { "category": "HOUSES", "text": "casas con servicio de auditoría" },
    { "category": "HOUSES", "text": "apartamentos con servicio de auditoría" },
    { "category": "HOUSES", "text": "casas con servicio de contabilidad" },
    { "category": "HOUSES", "text": "apartamentos con servicio de contabilidad" },
    { "category": "HOUSES", "text": "casas con servicio de finanzas" },
    { "category": "HOUSES", "text": "apartamentos con servicio de finanzas" },
    { "category": "HOUSES", "text": "casas con servicio de seguros" },
    { "category": "HOUSES", "text": "apartamentos con servicio de seguros" },
    { "category": "HOUSES", "text": "casas con servicio de inversiones" },
    { "category": "HOUSES", "text": "apartamentos con servicio de inversiones" },
    { "category": "HOUSES", "text": "casas con servicio de préstamos" },
    { "category": "HOUSES", "text": "apartamentos con servicio de préstamos" },
    { "category": "HOUSES", "text": "casas con servicio de hipotecas" },
    { "category": "HOUSES", "text": "apartamentos con servicio de hipotecas" },
    { "category": "HOUSES", "text": "casas con servicio de renta" },
    { "category": "HOUSES", "text": "apartamentos con servicio de renta" },
    { "category": "HOUSES", "text": "casas con servicio de compra" },
    { "category": "HOUSES", "text": "apartamentos con servicio de compra" },
    { "category": "HOUSES", "text": "casas con servicio de venta" },
    { "category": "HOUSES", "text": "apartamentos con servicio de venta" },
    { "category": "HOUSES", "text": "casas con servicio de traspaso" },
    { "category": "HOUSES", "text": "apartamentos con servicio de traspaso" },
    { "category": "HOUSES", "text": "casas con servicio de alquiler" },
    { "category": "HOUSES", "text": "apartamentos con servicio de alquiler" },
    { "category": "HOUSES", "text": "casas con servicio de cambio" },
    { "category": "HOUSES", "text": "apartamentos con servicio de cambio" },
    { "category": "HOUSES", "text": "casas con servicio de devolución" },
    { "category": "HOUSES", "text": "apartamentos con servicio de devolución" },
    { "category": "HOUSES", "text": "casas con servicio de garantía" },
    { "category": "HOUSES", "text": "apartamentos con servicio de garantía" },
    { "category": "HOUSES", "text": "casas con servicio de soporte técnico" },
    { "category": "HOUSES", "text": "apartamentos con servicio de soporte técnico" },
    { "category": "HOUSES", "text": "casas con servicio de atención al cliente" },
    { "category": "HOUSES", "text": "apartamentos con servicio de atención al cliente" },
    { "category": "HOUSES", "text": "casas con servicio de mesa de ayuda" },
    { "category": "HOUSES", "text": "apartamentos con servicio de mesa de ayuda" },
    { "category": "PRODUCT", "text": "zapatos" },
    { "category": "PRODUCT", "text": "camisetas" },
    { "category": "PRODUCT", "text": "jeans" },
    { "category": "PRODUCT", "text": "pantalones" },
    { "category": "PRODUCT", "text": "vestidos" },
    { "category": "PRODUCT", "text": "chaquetas" },
    { "category": "PRODUCT", "text": "abrigos" },
    { "category": "PRODUCT", "text": "sombreros" },
    { "category": "PRODUCT", "text": "guantes" },
    { "category": "PRODUCT", "text": "bufandas" },
    { "category": "PRODUCT", "text": "corbatas" },
    { "category": "PRODUCT", "text": "bolsos" },
    { "category": "PRODUCT", "text": "mochilas" },
    { "category": "PRODUCT", "text": "maletas" },
    { "category": "PRODUCT", "text": "joyas" },
    { "category": "PRODUCT", "text": "relojes" },
    { "category": "PRODUCT", "text": "gafas" },
    { "category": "PRODUCT", "text": "lentes" },
    { "category": "PRODUCT", "text": "maquillaje" },
    { "category": "PRODUCT", "text": "perfumes" },
    { "category": "PRODUCT", "text": "lociones" },
    { "category": "PRODUCT", "text": "cremas" },
    { "category": "PRODUCT", "text": "shampoo" },
    { "category": "PRODUCT", "text": "acondicionador" },
    { "category": "PRODUCT", "text": "peines" },
    { "category": "PRODUCT", "text": "cepillos" },
    { "category": "PRODUCT", "text": "secadores" },
    { "category": "PRODUCT", "text": "planchas" },
    { "category": "PRODUCT", "text": "computadoras" },
    { "category": "PRODUCT", "text": "portátiles" },
    { "category": "PRODUCT", "text": "tabletas" },
    { "category": "PRODUCT", "text": "teléfonos" },
    { "category": "PRODUCT", "text": "iPhone" },
    { "category": "PRODUCT", "text": "Samsung" },
    { "category": "PRODUCT", "text": "Huawei" },
    { "category": "PRODUCT", "text": "Xiaomi" },
    { "category": "PRODUCT", "text": "OnePlus" },
    { "category": "PRODUCT", "text": "Motorola" },
    { "category": "PRODUCT", "text": "Nokia" },
    { "category": "PRODUCT", "text": "Sony" },
    { "category": "PRODUCT", "text": "LG" },
    { "category": "PRODUCT", "text": "Google" },
    { "category": "PRODUCT", "text": "auriculares" },
    { "category": "PRODUCT", "text": "altavoces" },
    { "category": "PRODUCT", "text": "cámaras" },
    { "category": "PRODUCT", "text": "drones" },
    { "category": "PRODUCT", "text": "teclados" },
    { "category": "PRODUCT", "text": "ratones" },
    { "category": "PRODUCT", "text": "monitores" },
    { "category": "PRODUCT", "text": "impresoras" },
    { "category": "PRODUCT", "text": "escáneres" },
    { "category": "PRODUCT", "text": "televisores" },
    { "category": "PRODUCT", "text": "consolas" },
    { "category": "PRODUCT", "text": "juegos" },
    { "category": "PRODUCT", "text": "mandos" },
    { "category": "PRODUCT", "text": "baterías" },
    { "category": "PRODUCT", "text": "cargadores" },
    { "category": "PRODUCT", "text": "cables" },
    { "category": "PRODUCT", "text": "adaptadores" },
    { "category": "PRODUCT", "text": "memorias" },
    { "category": "PRODUCT", "text": "discos" },
    { "category": "PRODUCT", "text": "muebles" },
    { "category": "PRODUCT", "text": "sillas" },
    { "category": "PRODUCT", "text": "mesas" },
    { "category": "PRODUCT", "text": "camas" },
    { "category": "PRODUCT", "text": "sofás" },
    { "category": "PRODUCT", "text": "armarios" },
    { "category": "PRODUCT", "text": "cómodas" },
    { "category": "PRODUCT", "text": "espejos" },
    { "category": "PRODUCT", "text": "lámparas" },
    { "category": "PRODUCT", "text": "cojines" },
    { "category": "PRODUCT", "text": "alfombras" },
    { "category": "PRODUCT", "text": "cortinas" },
    { "category": "PRODUCT", "text": "mantas" },
    { "category": "PRODUCT", "text": "sábanas" },
    { "category": "PRODUCT", "text": "colchas" },
    { "category": "PRODUCT", "text": "edredones" },
    { "category": "PRODUCT", "text": "almohadas" },
    { "category": "PRODUCT", "text": "toallas" },
    { "category": "PRODUCT", "text": "trajes" },
    { "category": "PRODUCT", "text": "uniformes" },
    { "category": "PRODUCT", "text": "batas" },
    { "category": "PRODUCT", "text": "pijamas" },
    { "category": "PRODUCT", "text": "ropa" },
    { "category": "PRODUCT", "text": "interior" },
    { "category": "PRODUCT", "text": "calzado" },
    { "category": "PRODUCT", "text": "deporte" },
    { "category": "PRODUCT", "text": "natación" },
    { "category": "PRODUCT", "text": "fitness" },
    { "category": "PRODUCT", "text": "ciclismo" },
    { "category": "PRODUCT", "text": "escalada" },
    { "category": "PRODUCT", "text": "camping" },
    { "category": "PRODUCT", "text": "pesca" },
    { "category": "PRODUCT", "text": "caza" },
    { "category": "PRODUCT", "text": "golf" },
    { "category": "PRODUCT", "text": "tenis" },
    { "category": "PRODUCT", "text": "fútbol" },
    { "category": "PRODUCT", "text": "baloncesto" },
    { "category": "PRODUCT", "text": "voleibol" },
    { "category": "PRODUCT", "text": "béisbol" },
    { "category": "PRODUCT", "text": "rugby" },
    { "category": "PRODUCT", "text": "hockey" },
    { "category": "PRODUCT", "text": "patinaje" },
    { "category": "PRODUCT", "text": "esquí" },
    { "category": "PRODUCT", "text": "snowboard" },
    { "category": "PRODUCT", "text": "buceo" },
    { "category": "PRODUCT", "text": "surf" },
    { "category": "PRODUCT", "text": "kayak" },
    { "category": "PRODUCT", "text": "remo" },
    { "category": "PRODUCT", "text": "vela" },
    { "category": "PRODUCT", "text": "yoga" },
    { "category": "PRODUCT", "text": "pilates" },
    { "category": "PRODUCT", "text": "aeróbic" },
    { "category": "PRODUCT", "text": "danza" },
    { "category": "PRODUCT", "text": "macarons" },
    { "category": "PRODUCT", "text": "ballet" },
    { "category": "PRODUCT", "text": "patinaje" }
]
  